#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(_______, KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, _______, KC_TAB, KC_Q, KC_W, KC_R, KC_P, KC_Y, KC_J, KC_F, KC_O, KC_L, KC_SCLN, KC_EQL, KC_CAPS, KC_QUOT, KC_A, KC_S, KC_D, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_U, KC_MINS, KC_NO, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_K, KC_H, KC_COMM, KC_DOT, KC_UP, RSFT_T(KC_SLSH), KC_NO, KC_LCTL, KC_LALT, MO(2), KC_LGUI, LT(3,KC_SPC), KC_NO, RGUI_T(KC_ENT), TD(0), KC_LEFT, KC_DOWN, KC_RGHT),
    [1] = LAYOUT(_______, KC_ESC, KC_NLCK, KC_PEQL, KC_PSLS, KC_PAST, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DEL, KC_TRNS, _______, KC_TRNS, KC_P7, KC_P8, KC_P9, KC_PMNS, LSFT(KC_TAB), KC_NO, KC_NO, KC_LCBR, KC_RCBR, KC_TRNS, KC_TRNS, KC_MUTE, KC_TRNS, KC_P4, KC_P5, KC_P6, KC_PPLS, KC_NO, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_P1, KC_P2, KC_P3, KC_PENT, LGUI(KC_QUOT), KC_SCLN, KC_NO, KC_LT, KC_GT, KC_TRNS, KC_TRNS, KC_S, KC_TRNS, LALT_T(KC_PDOT), MACRO_0, LGUI_T(KC_P0), KC_TRNS, KC_NO, RGUI_T(KC_ENT), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [2] = LAYOUT(_______, KC_NLCK, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_DEL, _______, KC_CAPS, KC_F11, KC_F12, KC_F13, KC_F14, KC_F15, KC_MPLY, KC_NO, KC_NO, KC_NO, KC_NO, KC_RBRC, KC_SLEP, KC_GRV, RALT(KC_LBRC), RALT(KC_LCBR), RALT(KC_RBRC), RALT(KC_RCBR), LGUI(KC_DLR), RALT(KC_UNDS), RALT(KC_MINS), RALT(KC_SCLN), KC_PIPE, KC_NO, KC_LBRC, KC_NO, KC_LSFT, MACRO_1, MACRO_4, LCAG(KC_F10), KC_BTN3, USER03, MACRO_2, KC_MUTE, KC_VOLD, KC_VOLU, KC_PGUP, RSFT_T(KC_BSLS), KC_O, KC_RCTL, KC_RALT, KC_TRNS, KC_TRNS, KC_SPC, KC_NO, KC_PENT, LT(4,KC_RBRC), KC_HOME, KC_PGDN, KC_END),
	[3] = LAYOUT(_______, KC_NO, KC_1, KC_2, KC_3, KC_4, KC_5, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, _______, KC_NO, KC_WH_U, KC_NO, KC_UP, KC_NO, KC_HOME, KC_PGUP, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_GRV, KC_WH_D, KC_LEFT, KC_DOWN, KC_RGHT, KC_END, KC_PGDN, KC_NO, KC_NO, KC_PIPE, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_ACL0, KC_ACL1, KC_ACL2, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BTN1, KC_MS_U, KC_BTN2, KC_M, KC_LCTL, KC_LALT, LCAG(KC_NO), KC_LGUI, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_R),
    [4] = LAYOUT(_______, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_VAD, RGB_VAI, QK_BOOT, _______, KC_SLEP, KC_BRID, KC_BRIU, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_SPD, RGB_SPI, USER04, RGB_TOG, KC_MUTE, KC_VOLD, KC_VOLU, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_M_P, RGB_M_SN, RGB_M_SW, RGB_M_R, RGB_M_B, RGB_M_X, RGB_M_K, RGB_M_G, RGB_RMOD, RGB_MOD, RGB_SAI, RGB_M_T, KC_I, KC_RCTL, KC_NO, KC_TRNS, KC_NO, RGB_TOG, KC_NO, KC_NO, KC_TRNS, RGB_HUD, RGB_SAD, RGB_HUI)
};

#ifdef ENCODER_MAP_ENABLE

const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
    [0 ... 4] = { ENCODER_CCW_CW(KC_NO, KC_NO) }
};

#endif // ENCODER_MAP_ENABLE
