VIA_ENABLE = yes
VIAL_ENABLE = yes
RGB_MATRIX_ENABLE = yes
VIALRGB_ENABLE = yes
LTO_ENABLE = yes
AUDIO_ENABLE = no
CAPS_WORD_ENABLE = yes
OS_DETECTION_ENABLE = yes
BGK_SHIFTED_MOD_TAP_ENABLE = yes

# Not enough USB endpoints
CONSOLE_ENABLE = no
