/* SPDX-License-Identifier: GPL-2.0-or-later */

#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [0] = LAYOUT(
        KC_ESCAPE,KC_Q,    KC_W,    KC_D,    KC_P,    KC_F,    KC_J,    KC_L,    KC_O,    KC_Y,    KC_EQUAL,KC_BSPC,
    KC_QUOTE,KC_A,    KC_R,    KC_S,    KC_T,    KC_G,    KC_M,    KC_N,    KC_E,    KC_I,    KC_U,    KC_MINUS,
    KC_LSFT, LCTL_T(KC_Z),LALT_T(KC_X),KC_C,    KC_V,    KC_B,    RGUI_T(KC_K),RALT_T(KC_H),KC_UP,   KC_NO,   KC_RIGHT,KC_COMMA,KC_DOT,  RSFT_T(KC_SLASH),
    KC_LEFT, KC_NO, KC_DOWN,
    LGUI_T(KC_TAB),LT(2, KC_SPACE),LT(4, KC_ENTER)
    ),

    [1 ... (DYNAMIC_KEYMAP_LAYER_COUNT - 1)] = LAYOUT(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, QK_BOOT,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    )

};
