CONVERT_TO=promicro_rp2040

WS2812_DRIVER = vendor

VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes

CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes
OS_DETECTION_ENABLE = yes

SRC += bgk_reviung41.c

BGK_SHIFTED_MOD_TAP_ENABLE = yes

VIAL_INSECURE = yes
